### ISSUE TITLE
Unable to upgrade from 6.5.6 to 6.6.0

### ISSUE THREAD

**Issue by slubowsky** [borisdj/EFCore.BulkExtensions#1016]
.net 7 app. Trying to upgrade from 6.5.6 to 6.6.0 get error
```
 GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/49a1bb2b-12b0-475f-adbd-1560fc76be38/nuget/v3/flat2/efcore.bulkextensionscore/index.json
  GET https://api.nuget.org/v3-flatcontainer/efcore.bulkextensionscore/index.json
  GET https://nuget.devexpress.com/uRT3NwRChlKtV6VTmWQlXoai1Ktn8Qs2ieqXBmr1n8BhfAOIhv/api/FindPackagesById()?id='EFCore.BulkExtensionsCore'&semVerLevel=2.0.0
  GET https://www.myget.org/F/automapperdev/api/v3/flatcontainer/efcore.bulkextensionscore/index.json
  OK https://nuget.devexpress.com/uRT3NwRChlKtV6VTmWQlXoai1Ktn8Qs2ieqXBmr1n8BhfAOIhv/api/FindPackagesById()?id='EFCore.BulkExtensionsCore'&semVerLevel=2.0.0 50ms
  NotFound https://api.nuget.org/v3-flatcontainer/efcore.bulkextensionscore/index.json 143ms
  NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/49a1bb2b-12b0-475f-adbd-1560fc76be38/nuget/v3/flat2/efcore.bulkextensionscore/index.json 273ms
  NotFound https://www.myget.org/F/automapperdev/api/v3/flatcontainer/efcore.bulkextensionscore/index.json 394ms
NU1101: Unable to find package EFCore.BulkExtensionsCore. No packages exist with this id in source(s): automapper next, DevExpress Nuget server, dotnet8, Edi Tools, Microsoft Visual Studio Offline Packages, nuget.org
Package restore failed. Rolling back package changes
```

**Comment by matteotrapani** [comment]
I have the same problem with a .NET 6 application.

**Comment by NinjaCross** [comment]
Me too in a .NET 6 application.

**Comment by zyofeng** [comment]
https://api.nuget.org/v3-flatcontainer/efcore.bulkextensionscore/index.json

This nuget package is missing.

**Comment by borisdj** [comment]
6.6.0 is not yet targeting .Net 7.
It was a larger refactoring, the issue should be fixed with 6.6.2.

**Comment by slubowsky** [comment]
Excited to try out using EFCore.BulkExtensions.SqlServer instead of EFCore.BulkExtensions and not having unused Pomelo.EntityFrameworkCore.MySql being brought in and causing issues - but looks like still no 6.6.2 available for EFCore.BulkExtensions.SqlServer and 6.6.1 still getting above error.

**Comment by matteotrapani** [comment]
> 6.6.0 is not yet targeting .Net 7. It was a larger refactoring, the issue should be fixed with 6.6.2.

I can confirm that version 6.6.2 worked for me. Thanks!

**Comment by slubowsky** [comment]
EFCore.BulkExtensions.SqlServer 6.6.2 package installs successfully, but get runtime error:
`System.IO.FileNotFoundException: 'Could not load file or assembly 'EFCore.BulkExtensions.Common, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'`
