### ISSUE TITLE
`SetOutputIdentity: true` broken since update to .Net 9.0

### ISSUE THREAD

**Issue by angelaki** [borisdj/EFCore.BulkExtensions#1646]
I'm not quite sure (yet) if this issue was caused by an update of this lib or .Net 9.0 but right now the returned Ids are totally wrong! They weren't before my update. Is anyone already aware of this? Meanwhile I'm checking if the issue is caused by .Net 9.0 or this lib.

**Comment by angelaki** [comment]
The issue was introduced with `8.1.2`. - no relation to .Net 9.0 as far as I can tell. `9.0.0-rc.1` doesn't seam to solve it!

**Comment by jhfreestyle** [comment]
Hi, 
could it be related to this recent commit ?
https://github.com/borisdj/EFCore.BulkExtensions/issues/1578
#1578
I'm experiencing same issue since upgrade from 8.0.2 to 8.1.2, using sqlserver.
Return ids are wrong and mess up all related entites.

**Comment by borisdj** [comment]
Is this on SqlServer and are you using just BulkInsert or BulkInsertOrUpdate, or combineing it also with IncludeGraph?
And can you make a reproducale test.
Could be the same issue as https://github.com/borisdj/EFCore.BulkExtensions/issues/1629

**Comment by jhfreestyle** [comment]
Yes similar ! Using sqlserver, bulkinsertOrUpdate with setOutputId true and preserveOrder true. I'm also preloading new entites with id from -count to -1 (instead 0)
Will do more tests in coming days after christmas
Thanks

**Comment by angelaki** [comment]
Maybe I find some time for a repro in the first days of January. But yeah, guess could be related to this commit, checked the history myself and thought, that it actually could only be this one.

**Comment by PhideasAmbrosianus** [comment]
I can confirm I am seeing the same thing. Not sure if it's broken on everything or not, it seems like sometimes it's working and sometimes it is not for me.

I went from 3.1.1 to 3.1.2 and then I experienced the issue. I am replicating in MSSQL EXPRESS.

My implementation is this:
``` c#
// After this write, I check database and Ids SQL database assigned are not set back properly
await _context.BulkInsertAsync(SampleRecords, new BulkConfig { SetOutputIdentity = true });
```

No includes or graphs and this fails.

I noticed that in 3.1.1, the Ids database assigns are in order of the List<SampleRecord> I am providing to BulkInsertAsync.
In 3.1.2, the Ids aren't sequentially ordered - they're all there but kind of random.

The table in question does have navigations to other tables - but I also see it working correctly in navigations with other tables. I cannot see any logical pattern that causes one insert set to work Vs. others. In this app, I am doing multiple different BulkInserts of different types and some of them the Ids are assigned right and some are not.

**Comment by Liebeck** [comment]
We also noticed this "sometimes the order is random" in one of ours projects. Unfortunately, some of our production data was compromised and customer data got mixed :-(
Fortunately, we were able to fix it, but it took us 2 days :-(

**Comment by angelaki** [comment]
> We also noticed this "sometimes the order is random" in one of our projects. Unfortunately, some of our production data was compromised and customer data got mixed :-( Fortunately, we were able to fix it, but it took us 2 days :-( We pinned to BulkExtensions to version 8.1.1 for now

How did you solve it? By downgrading to version `8.1.2`? Or have you found another workaround? And yeah, blew up my production data pretty much, too.

**Comment by angelaki** [comment]
Argh! Felt again for this version `8.1.2`. @borisdj you need to take it offline! This one actually is super dangerous! Sorry I didn't find the time to create a repro, yet. But that one really messes with your data!

**Comment by borisdj** [comment]
New version with latest source are published v 8.1.3 for EF8 and v 9.0.1 for EF9.
Make a test for the issue with these versions.

**Comment by angelaki** [comment]
Yep, works for me 👌. @Liebeck can you maybe confirm?

@borisdj have you found an actual reason for this misbehavior? Want to get sure before switching to the latest version agains. Sorry but a bit afraid, that data-mess almost killed me. All appointments in my app got matched to different clients etc.. Wasn't that funny 😉

But never the less: thank you so much for your effort and this great library!!

**Comment by borisdj** [comment]
@angelaki sorry for the trouble.
There were several PRs merged and few more changes and commits in a short period before and after release of 8.1.2, and in addition was updating code to EF9.
It seems that this bug was short lived in the source and also did not show up with basic tests.
I wasn't able to pinpoint it exactly, as I did not get a reproducible sample.
Best would be to make some test for the ordering and have it run in your app before publish, especially when you upgrade the package to newer version.

**Comment by borisdj** [comment]
Sure, will add a test it if you manage to make it reproducible.

**Comment by borisdj** [comment]
You can send it to mail.

**Comment by angelaki** [comment]
@borisdj just sent you the file. I'm super excited if you can find the reason for this issue!

**Comment by borisdj** [comment]
@angelaki I did some more investigation but still no luck.
However you could try to take several versions from the commit history and put test into each to check.
Take a look at a list on this page (there is on with desc: *Version upgrade 8.1.2*):
https://github.com/borisdj/EFCore.BulkExtensions/commits/master/?after=481c0045dfc761528d400f4121b8fe5788a55fbf+69

If you find 2 sources that works correctly and incorrectly than by using Bisection method could with few hops isolate the one where the issue started, then we could inspect the changes in that commit or debug it.

**Comment by angelaki** [comment]
@borisdj but have you at least been able to reproduce the issue? Just to make sure. So it's just checking commit for commit for finding the first one having this issue, right?

**Comment by borisdj** [comment]
Not sure, I have downloaded this version, copied files from v8 folder to overwrite csproj(s).
Then added you your test and put the file you sent.
The test had passed, but there are not Asserts in the test, and not sure what order you expected.

Change a test to make it check for expected order and to fail if not valid.
Then when taking commit do not go one after another, insted take 2 that are say 29 commits apart, then take one in the middle, then middle from one side, etc (that hop method is called Bisection and it enable faster search)

**Comment by angelaki** [comment]
Ok, fair - this isn't a real test, yet 😉. But I hoped it might be enough for you to find the issue. If you run it twice with different versions and compare the created databases, you'll see they differ. Since the data provided shouldn't be used in a public test atm I thought it might be enough for you to find the issue and define a test actually hitting the problem's source.

And sure, not gonna check them one by one - but thanks for the hint!

**Comment by angelaki** [comment]
@borisdj Ok, here we got! Commit `5af41f2df4e6189e798cf7dc4dd3fc69ba37523b` breaks the behavior - for some reason?! Except the typo in the Commit Message I can't find any issue with it? I adopted the unit test above so it actually fails now.

Could you be so kind and take this final step to find the issue? Seams so weird to me ...

**Comment by kvpt** [comment]
The second change in this commit looks suspicious, comparing two values by checking the results of toString call is not a good way to do that.
@angelaki I made a [PR ](https://github.com/borisdj/EFCore.BulkExtensions/pull/1684) to fix that, not sure if it will fix your issue though.
You can run your repro with this code change to check if it change something ?
If it was the change that caused this issue to appear it should fix it.

**Comment by borisdj** [comment]
Seems that this line was the cause:
`var property = type.GetProperty(name, BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.Instance);`
it was changed from:
`var property = type.GetProperty(name, BindingFlags.DeclaredOnly);`

It is in a method `GetPropertyUnambiguous` that is called from 'OrderBy' function.
And looks like it is still broken, but still not sure why it is making this problem.

@Zinoberous maybe you have some ideas as you have made the PR:
https://github.com/borisdj/EFCore.BulkExtensions/commit/e7053e1c09f2a290a030dc9ad5ff2a1fd74a6051

**Comment by angelaki** [comment]
@borisdj yeah, actually still broken. So weired ... But guess you haven't checked any deep what is **actually** causing this issue? Lucky me hasn't relied on the latest version eventhough at the time testing the data constellation was working!

**Comment by borisdj** [comment]
@kvpt didn't catch the time to dig more into this.
Don't worry will sort it out soon.
Either will remove (or replace) the change that caused the issue, but first will to try to figure the exact reason why it is causing the issue.
In either way it will be fixed.

**Comment by angelaki** [comment]
Just noticed that I'm still stuck on the old version. Guess you're quite busy these days? Seeing some hard issues here, lately. I'd love to help but couldn't have found the issue the time I tried.

**Comment by Rookian** [comment]
I am not sure if this is related, but we also have issues with `BulkInsertAsync` and setting `SetOutputIdentity` to `true`.

Sometimes Ids are not loaded and remain 0.

**Comment by marcelwenka** [comment]
Hi, I just posted a comment referencing the same problem in a different [issue](https://github.com/borisdj/EFCore.BulkExtensions/issues/1629#issuecomment-4013281701), you might be interested in it checking out
